/* ==========================================================================
   The URL mirror — how tests reach production code
   --------------------------------------------------------------------------
   ComfyUI serves this pack at

       /extensions/<pack>/prompt_librarian/index.js

   and the four files that import from the core tree walk back out of that URL
   with a hardcoded number of `../`:

       prompt_librarian/index.js       ../../../scripts/app.js      (3)
       prompt_librarian/api/request.js ../../../../scripts/api.js   (4)
       prompt_store/index.js           ../../../scripts/app.js      (3)
       prompt_store/api.js             ../../../scripts/api.js      (3)

   The depth depends on how deep the file sits under web/, so MOVING A FILE ONE
   DIRECTORY BREAKS IT SILENTLY. Importing web/ in place would resolve those
   specifiers against the repo and never notice. So the tree is COPIED into a
   temp dir laid out exactly like ComfyUI serves it, and `imp()` is the only way
   a test is allowed to reach production code — a layout break then fails the
   whole suite instead of three files.

   COPY, NOT SYMLINK. Node resolves ESM specifiers against a module's *real*
   path, so a symlinked mount would make `../../../` escape back to the repo and
   defeat the entire point. `node --preserve-symlinks` does fix that, but it is a
   process-wide resolution change and needs elevated privileges to create
   symlinks on Windows. web/ is ~500 KB; a copy is ~5 ms.
   ========================================================================== */

import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { pathToFileURL } from "node:url";

/** Repo paths. `import.meta.dirname` is tests-js/harness/. */
export const ROOT = path.resolve(import.meta.dirname, "../..");
export const WEB = path.join(ROOT, "web");

/** ComfyUI mounts a pack under /extensions/<sanitised-dir-name>/. */
const PACK = "comfyui-prompt-library";

/* --------------------------------------------------------------------------
   The host stubs

   `<mount>/scripts/{app,api}.js` re-export off a single process-wide object so
   a test can swap the host without rebuilding the mount. These two files are
   evaluated ONCE per process and cache whatever they read, so `__PL_HOST__`
   must be MUTATED, never replaced — see harness/env.js.
   -------------------------------------------------------------------------- */
const STUB = (name) =>
  `// generated by tests-js/harness/mount.js — stands in for ComfyUI's ${name}\n` +
  `export const ${name} = (globalThis.__PL_HOST__ ??= {}).${name} ??= {};\n`;

/** Newest mtime under a directory, as the cache key for a built mount. */
function newestMtimeMs(dir) {
  let newest = 0;
  for (const entry of fs.readdirSync(dir, { withFileTypes: true, recursive: true })) {
    if (entry.isDirectory()) continue;
    const p = path.join(entry.parentPath ?? entry.path, entry.name);
    const m = fs.statSync(p).mtimeMs;
    if (m > newest) newest = m;
  }
  return Math.round(newest);
}

let cached = null;

/**
 * Build (or reuse) the mirrored mount and return its root.
 *
 * `node --test` runs one process per test file, so without a cross-process
 * cache every file would pay for its own copy. The key is the newest mtime
 * under web/, which makes a stale mount impossible: edit a file, get a new
 * mount. Built via mkdtemp + atomic rename so parallel processes can never
 * observe a half-copied tree.
 */
export function mountDir() {
  if (cached) return cached;

  const stamp = newestMtimeMs(WEB);
  const dest = path.join(os.tmpdir(), `pl-mount-${stamp}`);

  if (!fs.existsSync(path.join(dest, ".ready"))) {
    const stage = fs.mkdtempSync(path.join(os.tmpdir(), "pl-stage-"));
    fs.cpSync(WEB, path.join(stage, "extensions", PACK), { recursive: true });
    fs.mkdirSync(path.join(stage, "scripts"), { recursive: true });
    fs.writeFileSync(path.join(stage, "scripts", "app.js"), STUB("app"));
    fs.writeFileSync(path.join(stage, "scripts", "api.js"), STUB("api"));
    // Without this the mount's .js files are treated as CommonJS and every
    // `import` in the tree is a syntax error.
    fs.writeFileSync(path.join(stage, "package.json"), '{"type":"module"}\n');
    fs.writeFileSync(path.join(stage, ".ready"), String(stamp));
    try {
      fs.renameSync(stage, dest);
    } catch {
      // Another process won the race and already published an identical tree.
      fs.rmSync(stage, { recursive: true, force: true });
    }
    sweepStaleMounts(stamp);
  }

  cached = dest;
  return dest;
}

/** Drop mounts from earlier revisions, so /tmp does not grow without bound. */
function sweepStaleMounts(keepStamp) {
  const cutoff = Date.now() - 60 * 60 * 1000;
  let entries;
  try {
    entries = fs.readdirSync(os.tmpdir(), { withFileTypes: true });
  } catch {
    return;
  }
  for (const e of entries) {
    if (!e.isDirectory() || !e.name.startsWith("pl-mount-")) continue;
    if (e.name === `pl-mount-${keepStamp}`) continue;
    const p = path.join(os.tmpdir(), e.name);
    try {
      if (fs.statSync(p).mtimeMs < cutoff) fs.rmSync(p, { recursive: true, force: true });
    } catch {
      /* another process got there first */
    }
  }
}

/** Absolute file:// URL of a path relative to web/ inside the mount. */
export function url(rel) {
  return pathToFileURL(path.join(mountDir(), "extensions", PACK, rel)).href;
}

/** The mount's stub URLs, for asserting that the `../` walks land on them. */
export function scriptUrl(name) {
  return pathToFileURL(path.join(mountDir(), "scripts", name)).href;
}

/**
 * Seed the process-wide host with the minimum the two ENTRY files need at
 * import time.
 *
 * Every other module under web/ is inert on import, but the entries are
 * explicitly allowed side effects — `app.registerExtension(...)` — so importing
 * them against a bare `{}` throws. ComfyUI supplies a real `app`; this supplies
 * the smallest thing that is not a lie.
 *
 * MUTATES the existing object rather than replacing it: `<mount>/scripts/*.js`
 * captured these references on first evaluation and are never re-evaluated.
 */
export function seedHost() {
  const host = (globalThis.__PL_HOST__ ??= {});
  const app = (host.app ??= {});
  app._exts ??= [];
  app.registerExtension ??= function (ext) {
    this._exts.push(ext);
    return ext;
  };
  app.graph ??= { _nodes: [] };
  app.canvas ??= { selectNode() {}, setDirty() {} };
  const api = (host.api ??= {});
  api.fetchApi ??= () => Promise.reject(new Error("fetchApi not stubbed (see harness/net.js)"));
  api.addEventListener ??= () => {};
  api.removeEventListener ??= () => {};
  return host;
}

let bust = 0;

/**
 * Import a module by its path relative to web/. THE ONLY WAY TESTS REACH
 * PRODUCTION CODE.
 *
 * `{ fresh: true }` appends a cache-buster for a genuinely new module graph —
 * the same trick ComfyUI's `?v=` plays, and the hazard shared/singleton.js was
 * written against. Needed after resetting the singleton bag if the test asserts
 * on `api/lanes.js`'s `lanes` or `api/caps.js`'s `caps`, which are module-level
 * `const`s and therefore survive a bag reset in a cached graph.
 *
 * @param {string} rel e.g. "prompt_librarian/modal/shell.js"
 */
export function imp(rel, { fresh = false } = {}) {
  return import(url(rel) + (fresh ? `?t=${++bust}` : ""));
}

/** Every .js under web/, as paths relative to web/, sorted. */
export function allModules() {
  const out = [];
  for (const entry of fs.readdirSync(WEB, { withFileTypes: true, recursive: true })) {
    if (entry.isDirectory() || !entry.name.endsWith(".js")) continue;
    const abs = path.join(entry.parentPath ?? entry.path, entry.name);
    out.push(path.relative(WEB, abs).split(path.sep).join("/"));
  }
  return out.sort();
}

/** Read a file from the real web/ tree (for grep-style structural assertions). */
export function readWeb(rel) {
  return fs.readFileSync(path.join(WEB, rel), "utf8");
}
